// Generated by CoffeeScript 1.9.0
var Plane, accessors, bind, chain, emmiter, ref, scale;

ref = require('tools/object'), bind = ref.bind, chain = ref.chain, accessors = ref.accessors, emmiter = ref.emmiter;

scale = require('tools/d3-scales').scale;

Plane = (function() {
  function Plane() {
    var accessorList;
    if (!(this instanceof Plane)) {
      return new Plane;
    }
    accessorList = ['width', 'height', 'xdomain', 'ydomain', 'xrange', 'yrange', 'top', 'right', 'bottom', 'left', 'clamps'];
    chain(this).use(emmiter).use(accessors, accessorList);
  }

  return Plane;

})();

module.exports = Plane;

//# sourceMappingURL=group.js.map
