// Generated by CoffeeScript 1.3.3
var Handle, HandleSVG, d3,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Handle = require('ui-lib/handle');

d3 = require('d3');

HandleSVG = (function(_super) {

  __extends(HandleSVG, _super);

  function HandleSVG() {
    if (!(this instanceof HandleSVG)) {
      return new HandleSVG;
    }
    HandleSVG.__super__.constructor.call(this);
  }

  HandleSVG.prototype.center = function(x, y, rect) {
    return {
      x: x - rect.width * 0.5 - this.offsetx,
      y: y - rect.height * 0.5 - this.offsety
    };
  };

  HandleSVG.prototype.toDom = function($el) {
    return $el[0][0];
  };

  HandleSVG.prototype.domSize = function($el) {
    return this.toDom($el).getBoundingClientRect();
  };

  HandleSVG.prototype.append = function($head) {
    var h, w;
    HandleSVG.__super__.append.call(this, $head);
    this.canvas = d3.select(this.el).append('svg');
    this.context = this.canvas.append('g').attr("class", "context " + this.id);
    this.handle = $head(this.context);
    this.area = this.domSize(this.handle);
    w = this.area.width * 0.5;
    h = this.area.height * 0.5;
    this._xdomain[0] += w;
    this._ydomain[0] += h;
    this._xdomain[1] += w;
    this.updateScales();
    this.canvas.attr("width", this.width + this.offsetx).attr("height", this.height + this.offsety);
    return this.context.attr("transform", "translate(" + (this.left()) + ", " + (this.top()) + ")");
  };

  HandleSVG.prototype.update = function() {
    var x, y, _ref;
    _ref = this.center(this.x(), this.y(), this.area), x = _ref.x, y = _ref.y;
    this.handle.attr("transform", "translate(" + x + ", " + y + ")");
    return console.log(this.xToData(this.x()), this.yToData(this.y()));
  };

  return HandleSVG;

})(Handle);

module.exports = HandleSVG;
