// Generated by CoffeeScript 1.9.0
var Shape;

Shape = (function() {
  function Shape($context) {
    if (!(this instanceof Shape)) {
      return new Shape;
    }
  }

  return Shape;

})();

module.exports = Shape;

//# sourceMappingURL=shape.js.map
